### ISSUE TITLE
Destination /usr/share/go-server not writable

### ISSUE THREAD

**Issue by aloysius-lim** [gocd-contrib/ansible-gocd#39]
When using the server role, the following output is produced:

```
TASK [tpbrown.gocd/roles/server : create script for automated Go configuration backups to Git] ***
fatal: [gocd_server]: FAILED! => {"changed": true, "failed": true, "msg": "Destination /usr/share/go-server not writable"}
```

Here is the playbook:

```yaml
- hosts: gocd_server
  roles:
    - tpbrown.gocd/roles/common
    - tpbrown.gocd/roles/server
```

A simple fix would be to add `sudo: yes` to this step:

```yaml
# roles/server/tasks/go-server.yml
- name: create script for automated Go configuration backups to Git
  sudo: yes
  template: backup=no dest=/usr/share/go-server/ mode=0755 src=backup_to_git.sh
```
